This directory contains all raw data files or information where to download required raw data, which are needed to run the script amino_acid_cold_adaptation.Rmd.
All compressed files (*.tar.gz) have to be decompressed prior to use.

File descriptions:
1. 10k.cdhit.95.all.hifi.keep1s_clean.tsv.tar.gz: Contains predicted protein sequences for the Fram Strait viral contigs in this study (Available here: 10.6084/m9.figshare.28053119).
2. GOV2_proteins.tsv.tar.gz: Contains predicted protein sequences for the GOV2.0 dataset (Available here: 10.6084/m9.figshare.28053140).
3. fram.egc.wsc.merged_df.matrix_cvpg_tidy.csv: Contains abundances for all Fram Strait viral contigs in this study.
4. genomad-annotate_FRAM_contigs.tsv: Contains taxonomic predictions for all Fram Strait viral contigs in this study.
5. genomad-annotate_GOV2.0.tsv.tar.gz: Contains taxonomic predictions for the GOV2.0 dataset.
6. gov2.0.and.fram.metadata.17may2024.xlsx: Contains available environmental metadata for the Fram Strait and GOV2.0 samples.
7. metadata.date.txt: Contains additional metadata for the Fram Strait dataset.
